"""Updated tyre impression processing to include all pipeline output paths

Revision ID: bc09c644c37b
Revises: 3a3a40211772
Create Date: 2026-05-26 10:47:39.734321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc09c644c37b'
down_revision = '3a3a40211772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tyre_impression_processing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalised_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('enhanced_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('clean_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('feature_vector_json', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('match_results_json', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('pipeline_version', sa.Integer(), nullable=False))
        batch_op.drop_column('grayscale_path')
        batch_op.drop_column('preprocessing_version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tyre_impression_processing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preprocessing_version', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('grayscale_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('pipeline_version')
        batch_op.drop_column('match_results_json')
        batch_op.drop_column('feature_vector_json')
        batch_op.drop_column('clean_path')
        batch_op.drop_column('enhanced_path')
        batch_op.drop_column('normalised_path')

    # ### end Alembic commands ###
