"""Created tyre_impressions table

Revision ID: fd7773d2fa73
Revises: a06873882603
Create Date: 2026-05-21 13:23:24.663071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7773d2fa73'
down_revision = 'a06873882603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tyre_impressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'processed', 'matched', 'failed', name='tyreimpressionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tyre_impressions')
    # ### end Alembic commands ###
